/**
 * DiscoveryPage — cold-start landing.
 *
 * A scrollable discovery page that lets the user start a new topic in
 * multiple ways: typing in the composer, picking a recent topic,
 * tapping a mood chip, or (future) picking from favorites / edited
 * topics generated by dream. Every affordance ends at the same place:
 * a new or existing /chat/{id} with the appropriate playlist primed.
 */
import { useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { ChatInput } from './chat/ChatInput';
import { API_BASE } from '../config/api';
import type { Conversation } from '../types';

interface DiscoveryPageProps {
  conversations: Conversation[];
  userId: string | null;
  onSessionCreated?: () => void;
}

interface MoodChip {
  key: string;
  label: string;
  prompt: string;
}

const MOOD_CHIPS: MoodChip[] = [
  { key: 'focus', label: '🎯 专注', prompt: '给我一些适合专注工作的歌' },
  { key: 'sad', label: '🌧 伤心', prompt: '想听点伤感的歌' },
  { key: 'high_energy', label: '⚡️ 高能', prompt: '放点高能炸场的' },
  { key: 'chill', label: '🌿 放空', prompt: '想听点放松发呆的' },
  { key: 'surprise', label: '🎲 惊喜我', prompt: '随便推荐点我可能没听过的好歌' },
  { key: 'study', label: '📚 学习', prompt: '适合学习的背景音乐' },
  { key: 'workout', label: '💪 健身', prompt: '健身时听的歌' },
  { key: 'sleep', label: '🌙 助眠', prompt: '帮我入睡的歌' },
];

function formatArtwork(url: string | null | undefined, size = 400): string | null {
  if (!url) return null;
  return url.replace('{w}', String(size)).replace('{h}', String(size));
}

function displayTitle(c: Conversation): string {
  if (c.title) return c.title;
  if (c.last_message_preview) return c.last_message_preview;
  return 'Untitled';
}

export function DiscoveryPage({ conversations, userId, onSessionCreated }: DiscoveryPageProps) {
  const navigate = useNavigate();
  const [input, setInput] = useState('');
  const [isCreating, setIsCreating] = useState(false);

  // Create a session, optionally with an initial message that the chat
  // page will auto-send via useInitialMessage.
  const startNewTopic = useCallback(
    async (initialMessage?: string) => {
      if (!userId || isCreating) return;
      setIsCreating(true);
      try {
        const res = await fetch(`${API_BASE}/session/create`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ user_id: userId }),
        });
        if (!res.ok) throw new Error(`session/create ${res.status}`);
        const { session_id } = (await res.json()) as { session_id: string };
        onSessionCreated?.();
        navigate(`/chat/${session_id}`, {
          replace: true,
          state: initialMessage
            ? { isNewlyCreated: true, initialMessage }
            : { isNewlyCreated: true },
        });
      } catch (e) {
        console.error('[DiscoveryPage] new topic failed:', e);
        toast.error('Failed to start', { description: String(e).slice(0, 200) });
      } finally {
        setIsCreating(false);
      }
    },
    [userId, isCreating, navigate, onSessionCreated],
  );

  const handleSend = useCallback(() => {
    const trimmed = input.trim();
    if (!trimmed) return;
    startNewTopic(trimmed);
  }, [input, startNewTopic]);

  const handleMoodChip = useCallback(
    (chip: MoodChip) => {
      startNewTopic(chip.prompt);
    },
    [startNewTopic],
  );

  const handleTopicClick = useCallback(
    (id: string) => {
      navigate(`/chat/${id}`);
    },
    [navigate],
  );

  const recent = conversations.slice(0, 12);

  return (
    <div className="h-full w-full overflow-y-auto">
      <div className="max-w-3xl mx-auto px-6 py-10 space-y-10">
        {/* Composer */}
        <section>
          <h1 className="text-ink text-2xl font-display font-medium tracking-tight mb-1">
            听点啥？
          </h1>
          <p className="text-ink-3 text-sm mb-5">
            说一句你想听的——或从下面挑一个开始。
          </p>
          <ChatInput
            input={input}
            isLoading={isCreating}
            isDJSpeaking={false}
            isPlaying={false}
            onInputChange={setInput}
            onSend={handleSend}
          />
        </section>

        {/* Mood chips — "Try something" */}
        <section>
          <SectionHeader title="试试这些" hint="一句话起头" />
          <div className="flex flex-wrap gap-2">
            {MOOD_CHIPS.map((chip) => (
              <button
                key={chip.key}
                onClick={() => handleMoodChip(chip)}
                disabled={isCreating}
                className="px-4 py-2 glass hairline rounded-full text-[13px] text-ink-2 hover:text-ink hover:bg-ink/10 transition-all disabled:opacity-50"
              >
                {chip.label}
              </button>
            ))}
          </div>
        </section>

        {/* Recent topics */}
        {recent.length > 0 && (
          <section>
            <SectionHeader title="Recent" hint="续上次的歌单" />
            <div className="flex gap-3 overflow-x-auto pb-2 no-scrollbar -mx-6 px-6">
              {recent.map((c) => {
                const cover = formatArtwork(c.playlist_cover, 400);
                return (
                  <button
                    key={c.id}
                    onClick={() => handleTopicClick(c.id)}
                    className="group shrink-0 w-36 rounded-card overflow-hidden bg-chip hairline relative text-left transition-transform hover:-translate-y-0.5"
                  >
                    <div className="aspect-square w-full relative">
                      {cover ? (
                        <img
                          src={cover}
                          alt={displayTitle(c)}
                          className="absolute inset-0 w-full h-full object-cover"
                          loading="lazy"
                          draggable={false}
                        />
                      ) : (
                        <div className="absolute inset-0 bg-gradient-to-br from-chip-2 to-chip" />
                      )}
                      <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent" />
                      {(c.playlist_count ?? 0) > 0 && (
                        <div className="absolute top-2 right-2 px-1.5 py-0.5 rounded-full bg-black/40 backdrop-blur-md text-[10px] text-white/85 font-medium">
                          {c.playlist_count}
                        </div>
                      )}
                    </div>
                    <div className="p-2.5 text-[12px] font-display text-ink font-medium leading-snug line-clamp-2 min-h-[3rem]">
                      {displayTitle(c)}
                    </div>
                  </button>
                );
              })}
            </div>
          </section>
        )}

        {/* 收藏夹 — placeholder */}
        <section>
          <SectionHeader title="收藏夹" hint="导入 Apple Music / Spotify 歌单（即将上线）" />
          <PlaceholderRow lines={[
            '把你在其他软件里的歌单接进来',
            '一键导入 Apple Music 资料库 · Spotify 歌单 · 自定义清单',
          ]} />
        </section>

        {/* 编辑 topic — placeholder for dream */}
        <section>
          <SectionHeader title="编辑 topic" hint="AI 为你打磨的歌单（dream 模式上线后启用）" />
          <PlaceholderRow lines={[
            'AI 根据你的听歌历史，每天产出一份「今日推荐」',
            '基于上下文（时间 / 天气 / 心情）的智能策划',
          ]} />
        </section>
      </div>
    </div>
  );
}

function SectionHeader({ title, hint }: { title: string; hint?: string }) {
  return (
    <div className="flex items-baseline justify-between mb-3">
      <h2 className="text-ink text-[15px] font-medium font-display tracking-tight">{title}</h2>
      {hint && <span className="text-ink-4 text-[12px]">{hint}</span>}
    </div>
  );
}

function PlaceholderRow({ lines }: { lines: string[] }) {
  return (
    <div className="glass hairline rounded-card p-5 space-y-2">
      {lines.map((line, i) => (
        <div key={i} className="text-ink-3 text-[13px] flex items-start gap-2">
          <span className="text-ink-4 mt-0.5">·</span>
          <span>{line}</span>
        </div>
      ))}
    </div>
  );
}
