name = "playheads-landing"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "playheads-db"
database_id = "31cba35f-8e23-46eb-880f-19d667c0946b"

[triggers]
crons = ["0 */4 * * *"]
