name = "playheads-landing"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "dist", binding = "ASSETS" }

[triggers]
crons = ["0 */4 * * *"]
